services:
  mosquitto:
    image: eclipse-mosquitto 
    container_name: mosquitto
    ports:
      - "1890:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  
  nodered:
    image: nodered/node-red
    container_name: nodered
    ports:
      - "1900:1880"
    volumes:
      - nodered_data:/data
    depends_on:
      - mosquitto

  influxdb:
    image: influxdb:1.8
    container_name: influxdb-server
    ports:
      - "8090:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3900:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  nodered_data:
  influxdb_data:
  grafana_data: